spring.datasource.url=jdbc:postgresql://localhost:5432/smart_attendance
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Security JWT
jwt.secret=your_super_secret_key_which_must_be_long_enough
jwt.expiration=86400000
